# Naive Bayes Classifier

In [1]:
#classification for allelectronics dataset

import pandas as pd
from numpy import array
from sklearn.naive_bayes import GaussianNB

## Loading the dataset

In [2]:
#load data

data = pd.read_csv("allelectronics.csv", usecols=range(1,6))
print(array(data))

[['youth' 'high' 'no' 'fair' 'no']
 ['youth' 'high' 'no' 'excellent' 'no']
 ['middle_aged' 'high' 'no' 'fair' 'yes']
 ['senior' 'medium' 'no' 'fair' 'yes']
 ['senior' 'low' 'yes' 'fair' 'yes']
 ['senior' 'low' 'yes' 'excellent' 'no']
 ['middle_aged' 'low' 'yes' 'excellent' 'yes']
 ['youth' 'medium' 'no' 'fair' 'no']
 ['youth' 'low' 'yes' 'fair' 'yes']
 ['senior' 'medium' 'yes' 'fair' 'yes']
 ['youth' 'medium' 'yes' 'excellent' 'yes']
 ['middle_aged' 'medium' 'no' 'excellent' 'yes']
 ['middle_aged' 'high' 'yes' 'fair' 'yes']
 ['senior' 'medium' 'no' 'excellent' 'no']]


## Loading the encoded dataset

In [3]:
#encode the dataset into numeric values.

allelectronics = pd.read_csv("allelectronicsencoding.csv",header=None, skiprows=1, usecols=range(1,6))
allelectronics = array(allelectronics)
print(allelectronics)

[[0 2 0 0 0]
 [0 2 0 1 0]
 [1 2 0 0 1]
 [2 1 0 0 1]
 [2 0 1 0 1]
 [2 0 1 1 0]
 [1 0 1 1 1]
 [0 1 0 0 0]
 [0 0 1 0 1]
 [2 1 1 0 1]
 [0 1 1 1 1]
 [1 1 0 1 1]
 [1 2 1 0 1]
 [2 1 0 1 0]]


## Splitting features and class

In [4]:
# Splitting Features and Target

# X_train = age, income, student, credit_rating
X_train = allelectronics[:, 0:4]

# Y_train = buys_computer
Y_train = allelectronics[:, 4:5]

# (n, m) = n rows m columns
print(X_train.shape) 
print(Y_train.shape)

(14, 4)
(14, 1)


## Learning Step (classification model construction step)

In [ ]:
# Classifier
gnb = GaussianNB()

# Model Construction
gnb = gnb.fit(X_train, Y_train)

## Classification Step (classification model usage step)

### This step is to classify whether a person buys a computer while we know that he/she is a young student and his/her income and credit_rating is fair.

In [6]:
# Model Usage

#[0,1,1,1] = [age = young, income = fair, student = yes, credit_rating = fair]
X_test = array([[0,1,1,0]])

pred_test = gnb.predict(X_test)

# 1 is yes and 0 is no.
if pred_test == 1:
    print("YES")
else :
    print("NO")

YES
